version: '3.8'
services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '8080:5432'
  app:
    build:
      context: .
      dockerfile: /Dockerfile
    ports:
      - '8080:5432'
